spring:
  mqtt: #MQTT配置信息
    username: null #MQTT-用户名
    password: null #MQTT-密码
    url: tcp://10.0.103.4:1883 #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
    client:
      id: ${random.value} #MQTT-连接服务器默认客户端ID
    default:
      topic: topic #MQTT-默认的消息推送主题，实际可在调用接口时指定
    completionTimeout: 3000
